<a href="https://colab.research.google.com/github/dr-bankert-augustana/PHYS_313/blob/main/PHYS_313_DataFrames_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a name="Notebook-Start"></a>

---

<font size = 7> <b> Introduction to Pandas and DataFrames </b> </font>

---

<a name="Introduction"></a>

---

<font size = 6> <b> 2. Introduction </b> </font>

---

<font size = 5> <b> 2.1 What is Pandas? </b> </font>

<p align="justify">
In computational physics (and any kind of scientific computing) managing, analyzing, and visualizing data efficiently is essential. The Pandas library in Python is a powerful and flexible tool designed specifically for data manipulation and analysis. At its core, Pandas introduces two primary data structures.
</p>

  * The <a href = #Definition-Series></b>Series</b></a> (a one-dimensional array)
  
  * The <a href = #Definition-Series></b>DataFrame</b></a> (a two-dimensional table similar to an Excel spreadsheet).
  
<br>

<p align="justify">
These new data structures allow us to label our data, perform complex operations with simple syntax, and handle missing values or mixed data types gracefully.
</p>

[Return to Top](#Notebook-Start)

<a name="Creating-DF"></a>

---

<font size = 6> <b> 3. Creating DataFrames </b> </font>

---

<font size=5><b>3.1 Creating DataFrames From Dictionaries</b></font>

<p align="justify">
One of the most straightforward ways to create a DataFrame in Pandas is by using a Python dictionary. In this approach, each key in the dictionary represents a column name, and the corresponding value is a list (or array) containing the data for that column. Pandas automatically aligns these values by row, as long as the lists are of equal length.
</p>

<br>

<p align="justify">
This method is especially useful when you already have structured data in Python (for example, experimental measurements or simulation results stored in variables) and you want to organize them into a tabular format for further analysis.
</p>

<br>

<b>Code Example:</b>

In the following code cell, we create a simple DataFrame from some synthetic experimental data.

In [1]:
# Import the Pandas Library:

import pandas as pd

# Create a dictionary of data:

data = {
    "Time (s)": [0, 1, 2, 3, 4],
    "Position (m)": [0, 2.5, 10, 22.5, 40],
    "Velocity (m/s)": [0, 5, 10, 15, 20]
}

# Convert the dictionary into a DataFrame:

df = pd.DataFrame(data)

# Display the DataFrame:

display(df)

   Time (s)  Position (m)  Velocity (m/s)
0         0           0.0               0
1         1           2.5               5
2         2          10.0              10
3         3          22.5              15
4         4          40.0              20

<b>Understanding the Output</b>

<p align="justify">
This printed table looks very similar to what you'd see in a spreadsheet like Excel or Google Sheets:
</p>

  * <b>Columns:</b> Each column corresponds to one of the keys from the dictionary. In this case, we have three columns: <code>Time (s)</code>, <code>Position (m)</code>, and <code>Velocity (m/s)</code>. These serve the same purpose as column headers in a spreadsheet, labeling the type of data in each column.

  * <b>Rows:</b> Each row contains a single set of related data points; one time value, one position, and one velocity. These rows represent observations or measurements taken at different points in time.

  * <b>Index column (on the far left):</b> By default, Pandas automatically adds an index column starting from 0. This index uniquely identifies each row, similar to row numbers in a spreadsheet. While it doesn't carry physical meaning in this example, it becomes very useful when accessing or referencing specific rows programmatically.

<br>

<p align="justify">
So, in essence, the Pandas DataFrame behaves much like a digital spreadsheet, but with the added power of Python. As we see in this lesson, you can apply mathematical operations, filter rows, compute statistics, and generate plots all from this structured format, making it a key tool in your computational physics toolkit.
</p>

<center>$\rule$</center>
<font size=5><b>3.2 Creating a DataFrame from a CSV File</b></font>

<p align="justify">
In real-world physics work, it's common to store data in external files; especially CSV (Comma-Separated Values) files. These are simple text files where each line represents a row of data, and values are separated by commas. Think of it as a stripped-down spreadsheet that can be easily shared and read by many programs. In fact, you can export a spreadsheet from any common program (such as Excel, Google Sheets, etc) as a CSV file.
</p>

<br>

<p align="justify">
Pandas makes it incredibly easy to read data from a CSV file and convert it into a DataFrame using the <code>read_csv()</code> function.
</p>

<br>

<b>Code Example:</b>

In the following code cell, we read in the data from a CSV file into a Pandas DataFrame.

In [2]:
# Set the location of the CSV file (can be local or a website):

url = "https://github.com/dr-bankert-augustana/PHYS_313/raw/main/Data/saturated-water-by-temp.txt"

# Turn the CSV data into a Pandas DataFrame:

full_data_df = pd.read_csv(url, sep="\t")

# Display the DataFrame:

display(full_data_df)

,Temperature (C),Pressure (MPa),"Density (l, kg/m3)","Volume (l, m3/kg)","Internal Energy (l, kJ/kg)","Enthalpy (l, kJ/kg)","Entropy (l, J/g*K)","Cv (l, J/g*K)","Cp (l, J/g*K)","Sound Spd. (l, m/s)",...,"Volume (v, m3/kg)","Internal Energy (v, kJ/kg)","Enthalpy (v, kJ/kg)","Entropy (v, J/g*K)","Cv (v, J/g*K)","Cp (v, J/g*K)","Sound Spd. (v, m/s)","Joule-Thomson (v, K/MPa)","Viscosity (v, Pa*s)","Therm. Cond. (v, W/m*K)"
0,1.0,0.000657,999.85099,0.001000,4.176053,4.176710,0.015260,4.215230,4.216599,1407.20640,...,192.438780,2376.2825,2502.7312,9.129083,1.419204,1.885335,409.71719,574.219680,0.000009,0.016824
1,2.0,0.000706,999.89254,0.001000,8.391082,8.391788,0.030607,4.212901,4.213496,1412.07520,...,179.757810,2377.6585,2504.5650,9.102652,1.420038,1.886339,410.44043,556.226070,0.000009,0.016889
2,3.0,0.000758,999.91707,0.001000,12.603120,12.603879,0.045888,4.210472,4.210617,1416.83020,...,168.008440,2379.0341,2506.3980,9.076466,1.420879,1.887352,411.16199,538.838600,0.000009,0.016953
3,4.0,0.000814,999.92513,0.001000,16.812386,16.813199,0.061103,4.207947,4.207947,1421.47380,...,157.115760,2380.4091,2508.2303,9.050521,1.421726,1.888375,411.88188,522.040700,0.000009,0.017018
4,5.0,0.000873,999.91724,0.001000,21.019078,21.019951,0.076254,4.205330,4.205470,1426.00800,...,147.011340,2381.7835,2510.0619,9.024814,1.422578,1.889408,412.60012,505.815900,0.000009,0.017083
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368,369.0,20.793214,462.18310,0.002164,1828.537300,1873.526500,4.085300,3.738594,35.945858,373.91929,...,0.005188,2248.7582,2356.6230,4.837611,4.465259,76.121199,369.05993,5.103509,0.000029,0.316341
369,370.0,21.043563,451.42565,0.002215,1844.071500,1890.687200,4.111150,3.838962,45.155176,359.87103,...,0.004954,2230.2593,2334.5183,4.801240,4.566402,96.597620,362.82908,4.950732,0.000030,0.349462
370,371.0,21.297108,438.63778,0.002280,1862.021300,1910.574200,4.141162,3.979315,62.350748,343.27877,...,0.004699,2208.2205,2308.3055,4.758613,4.698954,132.213230,355.12613,4.776180,0.000031,0.396062
371,372.0,21.553947,422.25967,0.002368,1884.210900,1935.255200,4.178522,4.212179,102.148990,321.80123,...,0.004408,2180.4973,2275.5162,4.705935,4.888148,207.395340,344.80135,4.568537,0.000032,0.469921
372,373.0,21.814167,398.68122,0.002508,1914.955700,1969.671600,4.230843,4.697283,243.777110,291.99948,...,0.004045,2141.5764,2229.8147,4.633448,5.210303,450.734520,328.42228,4.303203,0.000034,0.622452

<center>$\rule$</center>
<font size=5><b>3.3 Creating a DataFrame from Columns</b></font>

Let us start by creating a simple DataFrame with Column 'A' = [0.1, 0.2, 0.3] and Column 'B' = [10, 20, 30].

<b>Code Example</b>

In [3]:
table_df = pd.DataFrame({'A':[0.1, 0.2, 0.3],'B':[10 , 20, 30]})

display(table_df)

     A   B
0  0.1  10
1  0.2  20
2  0.3  30

<center>$\rule$</center>
<font size=5><b>3.4 Adding a Column to a DataFrame</b></font>

We can easily add new columns to our DataFrame objects by giving them a name and some data.

<br>

<b>Code Example</b>

In [4]:
# We can copy an existing column:

table_df['C'] = table_df['A']

# We can also, make one from new data:

table_df['D'] = [7.0, 8.0, 9.0]

table_df

     A   B    C    D
0  0.1  10  0.1  7.0
1  0.2  20  0.2  8.0
2  0.3  30  0.3  9.0

<center>$\rule$</center>
<font size=5><b>3.5 Renaming a column in a DataFrame</b></font>

We can also change the names of the columns in our DataFrame.

<br>

<b>Code Example</b>

In [5]:
table_rename_df = table_df.rename(columns = {"A" : "E"})

table_rename_df

     E   B    C    D
0  0.1  10  0.1  7.0
1  0.2  20  0.2  8.0
2  0.3  30  0.3  9.0

---

## Series methods [sum], [multiply], [add], ...

Every column of a DataFrame is a pandas Series object, and is equipped with many useful methods that can be used to do computations.

### Example 1: Find the sum of a column:

---

In [6]:
print(table_df['B'].sum())

60

---

### Example 2: Add two columns:

---

In [7]:
table_df['E'] = table_df['A'].add(table_df['B'])
table_df

     A   B    C    D     E
0  0.1  10  0.1  7.0  10.1
1  0.2  20  0.2  8.0  20.2
2  0.3  30  0.3  9.0  30.3

---

### Example 3: Multiply two columns:

---

In [8]:
table_df['F'] = table_df['A'].multiply(table_df['B'])
table_df

     A   B    C    D     E    F
0  0.1  10  0.1  7.0  10.1  1.0
1  0.2  20  0.2  8.0  20.2  4.0
2  0.3  30  0.3  9.0  30.3  9.0

---

### Example 4: Get the minimum and maximum values of a column:

---

In [9]:
f_minimum = table_df['F'].min()
f_maximum = table_df['F'].max()

print("Minimum of column 'F' is: " + str(f_minimum))
print()
print("Maximum of column 'F' is: " + str(f_maximum))

Minimum of column 'F' is: 1.0

Maximum of column 'F' is: 9.0

[Return to Top](#Notebook-Start)

<a name="Explore-DF"></a>

---

<font size = 6> <b> 4. Exploring a DataFrame </b> </font>

---

<font size=5><b>4.1 Methods for Exploring the DataFrame</b></font>

<p align="justify">
Once you've loaded data into a Pandas DataFrame (whether from a dictionary, CSV file, or another source) it's important to understand what's in it and whether it looks right before jumping into analysis. Pandas provides several built-in methods to help us quickly explore the dataset.
</p>

<center>$\rule$</center>
<font size=5><b>4.2 <code>info()</code>: Structure and Metadata</b></font>

This method gives you a concise summary of the DataFrame’s structure, including:

  * The number of rows and columns

  * Column names and data types (int64, float64, object, etc.)

  * Number of non-null (i.e. non-missing) values in each column

  * Memory usage

<br>

<p align="justify">
<b>Why it's useful:</b> Helps you quickly check for missing data and see if the data types are appropriate (e.g. no text where numbers should be).
</p>

<br>

<b>Code Example:</b>

In the following code cell, we use <code>info()</code> to look at our celebrity heights DataFrame.

In [10]:
# Display the Output of info():

display(full_data_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 373 entries, 0 to 372
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Temperature (C)             373 non-null    float64
 1   Pressure (MPa)              373 non-null    float64
 2   Density (l, kg/m3)          373 non-null    float64
 3   Volume (l, m3/kg)           373 non-null    float64
 4   Internal Energy (l, kJ/kg)  373 non-null    float64
 5   Enthalpy (l, kJ/kg)         373 non-null    float64
 6   Entropy (l, J/g*K)          373 non-null    float64
 7   Cv (l, J/g*K)               373 non-null    float64
 8   Cp (l, J/g*K)               373 non-null    float64
 9   Sound Spd. (l, m/s)         373 non-null    float64
 10  Joule-Thomson (l, K/MPa)    373 non-null    float64
 11  Viscosity (l, Pa*s)         373 non-null    float64
 12  Therm. Cond. (l, W/m*K)     373 non-null    float64
 13  Surf. Tension (l, N/m)      373 non-null    float64
 14  Density (v, kg/m3)          373 non-null    float64
 15  Volume (v, m3/kg)           373 non-null    float64
 16  Internal Energy (v, kJ/kg)  373 non-null    float64
 17  Enthalpy (v, kJ/kg)         373 non-null    float64
 18  Entropy (v, J/g*K)          373 non-null    float64
 19  Cv (v, J/g*K)               373 non-null    float64
 20  Cp (v, J/g*K)               373 non-null    float64
 21  Sound Spd. (v, m/s)         373 non-null    float64
 22  Joule-Thomson (v, K/MPa)    373 non-null    float64
 23  Viscosity (v, Pa*s)         373 non-null    float64
 24  Therm. Cond. (v, W/m*K)     373 non-null    float64
dtypes: float64(25)
memory usage: 73.0 KB

None

<center>$\rule$</center>
<font size=5><b>4.3 <code>df.describe()</code>: Summary Statistics</b></font>

This method computes common statistical summaries for each numeric column, such as:

* Count

* Mean

* Standard deviation

* Min and max

* 25th, 50th (median), and 75th percentiles

<br>

<b>Why it's useful</b>: Provides a quick overview of the data's distribution and helps spot unusual values (e.g., extreme outliers or zero variance).

<br>

<b>Code Example:</b>

In the following code cell, we use <code>describe()</code> to look at our celebrity heights DataFrame.

<center>$\rule$</center>
<font size=5><b>4.4 <code>head(n)</code>: Display First n Rows (Default: 5)</b></font>

Displays the first few rows of the DataFrame. This is often your first stop after loading data to verify that everything looks as expected (column names, data format, etc.).

<br>

<b>Code Example:</b>

In the following code cell, we use <code>head(n)</code> to look at our celebrity heights DataFrame.

In [11]:
# Display the first 5 rows of the full data DataFrame:

print("First 5 rows:")

display(full_data_df.head())

print()

# Display the first 10 rows of the full data DataFrame:

print("First 10 rows:")

display(full_data_df.head(10))

First 5 rows:

,Temperature (C),Pressure (MPa),"Density (l, kg/m3)","Volume (l, m3/kg)","Internal Energy (l, kJ/kg)","Enthalpy (l, kJ/kg)","Entropy (l, J/g*K)","Cv (l, J/g*K)","Cp (l, J/g*K)","Sound Spd. (l, m/s)",...,"Volume (v, m3/kg)","Internal Energy (v, kJ/kg)","Enthalpy (v, kJ/kg)","Entropy (v, J/g*K)","Cv (v, J/g*K)","Cp (v, J/g*K)","Sound Spd. (v, m/s)","Joule-Thomson (v, K/MPa)","Viscosity (v, Pa*s)","Therm. Cond. (v, W/m*K)"
0,1.0,0.000657,999.85099,0.001,4.176053,4.176710,0.015260,4.215230,4.216599,1407.2064,...,192.43878,2376.2825,2502.7312,9.129083,1.419204,1.885335,409.71719,574.21968,0.000009,0.016824
1,2.0,0.000706,999.89254,0.001,8.391082,8.391788,0.030607,4.212901,4.213496,1412.0752,...,179.75781,2377.6585,2504.5650,9.102652,1.420038,1.886339,410.44043,556.22607,0.000009,0.016889
2,3.0,0.000758,999.91707,0.001,12.603120,12.603879,0.045888,4.210472,4.210617,1416.8302,...,168.00844,2379.0341,2506.3980,9.076466,1.420879,1.887352,411.16199,538.83860,0.000009,0.016953
3,4.0,0.000814,999.92513,0.001,16.812386,16.813199,0.061103,4.207947,4.207947,1421.4738,...,157.11576,2380.4091,2508.2303,9.050521,1.421726,1.888375,411.88188,522.04070,0.000009,0.017018
4,5.0,0.000873,999.91724,0.001,21.019078,21.019951,0.076254,4.205330,4.205470,1426.0080,...,147.01134,2381.7835,2510.0619,9.024814,1.422578,1.889408,412.60012,505.81590,0.000009,0.017083

First 10 rows:

,Temperature (C),Pressure (MPa),"Density (l, kg/m3)","Volume (l, m3/kg)","Internal Energy (l, kJ/kg)","Enthalpy (l, kJ/kg)","Entropy (l, J/g*K)","Cv (l, J/g*K)","Cp (l, J/g*K)","Sound Spd. (l, m/s)",...,"Volume (v, m3/kg)","Internal Energy (v, kJ/kg)","Enthalpy (v, kJ/kg)","Entropy (v, J/g*K)","Cv (v, J/g*K)","Cp (v, J/g*K)","Sound Spd. (v, m/s)","Joule-Thomson (v, K/MPa)","Viscosity (v, Pa*s)","Therm. Cond. (v, W/m*K)"
0,1.0,0.000657,999.85099,0.001,4.176053,4.176710,0.015260,4.215230,4.216599,1407.2064,...,192.43878,2376.2825,2502.7312,9.129083,1.419204,1.885335,409.71719,574.21968,0.000009,0.016824
1,2.0,0.000706,999.89254,0.001,8.391082,8.391788,0.030607,4.212901,4.213496,1412.0752,...,179.75781,2377.6585,2504.5650,9.102652,1.420038,1.886339,410.44043,556.22607,0.000009,0.016889
2,3.0,0.000758,999.91707,0.001,12.603120,12.603879,0.045888,4.210472,4.210617,1416.8302,...,168.00844,2379.0341,2506.3980,9.076466,1.420879,1.887352,411.16199,538.83860,0.000009,0.016953
3,4.0,0.000814,999.92513,0.001,16.812386,16.813199,0.061103,4.207947,4.207947,1421.4738,...,157.11576,2380.4091,2508.2303,9.050521,1.421726,1.888375,411.88188,522.04070,0.000009,0.017018
4,5.0,0.000873,999.91724,0.001,21.019078,21.019951,0.076254,4.205330,4.205470,1426.0080,...,147.01134,2381.7835,2510.0619,9.024814,1.422578,1.889408,412.60012,505.81590,0.000009,0.017083
5,6.0,0.000935,999.89388,0.001,25.223384,25.224320,0.091342,4.202624,4.203172,1430.4350,...,137.63268,2383.1574,2511.8928,8.999343,1.423436,1.890449,413.31670,490.14791,0.000009,0.017149
6,7.0,0.001002,999.85552,0.001,29.425477,29.426479,0.106368,4.199834,4.201041,1434.7568,...,128.92264,2384.5307,2513.7229,8.974105,1.424298,1.891499,414.03165,475.02058,0.000009,0.017214
7,8.0,0.001073,999.80258,0.001,33.625516,33.626589,0.121334,4.196962,4.199065,1438.9753,...,120.82895,2385.9033,2515.5522,8.949097,1.425165,1.892558,414.74497,460.41798,0.000009,0.017280
8,9.0,0.001148,999.73549,0.001,37.823653,37.824802,0.136239,4.194011,4.197235,1443.0924,...,113.30375,2387.2754,2517.3807,8.924316,1.426037,1.893625,415.45667,446.32434,0.000009,0.017346
9,10.0,0.001228,999.65462,0.001,42.020027,42.021256,0.151086,4.190984,4.195539,1447.1101,...,106.30323,2388.6468,2519.2083,8.899760,1.426913,1.894700,416.16675,432.72414,0.000009,0.017412

<center>$\rule$</center>
<font size=5><b>4.5 <code>tail(n)</code>: Display Last n Rows (Default: 5)</b></font>

Displays the last few rows of the DataFrame. This is useful to:

  * See the end of a time series

  * Verify that data loaded completely

  * Check for anomalies or formatting issues at the bottom of the file

<br>

<b>Code Example:</b>

In the following code cell, we use <code>tail(n)</code> to look at our celebrity heights DataFrame.

In [12]:
# Display the last 5 rows of the full data DataFrame:

print("Last 5 rows:")

display(full_data_df.tail())

print()

# Display the last 10 rows of the full data DataFrame:

print("Last 10 rows:")

display(full_data_df.tail(10))

Last 5 rows:

,Temperature (C),Pressure (MPa),"Density (l, kg/m3)","Volume (l, m3/kg)","Internal Energy (l, kJ/kg)","Enthalpy (l, kJ/kg)","Entropy (l, J/g*K)","Cv (l, J/g*K)","Cp (l, J/g*K)","Sound Spd. (l, m/s)",...,"Volume (v, m3/kg)","Internal Energy (v, kJ/kg)","Enthalpy (v, kJ/kg)","Entropy (v, J/g*K)","Cv (v, J/g*K)","Cp (v, J/g*K)","Sound Spd. (v, m/s)","Joule-Thomson (v, K/MPa)","Viscosity (v, Pa*s)","Therm. Cond. (v, W/m*K)"
368,369.0,20.793214,462.18310,0.002164,1828.5373,1873.5265,4.085300,3.738594,35.945858,373.91929,...,0.005188,2248.7582,2356.6230,4.837611,4.465259,76.121199,369.05993,5.103509,0.000029,0.316341
369,370.0,21.043563,451.42565,0.002215,1844.0715,1890.6872,4.111150,3.838962,45.155176,359.87103,...,0.004954,2230.2593,2334.5183,4.801240,4.566402,96.597620,362.82908,4.950732,0.000030,0.349462
370,371.0,21.297108,438.63778,0.002280,1862.0213,1910.5742,4.141162,3.979315,62.350748,343.27877,...,0.004699,2208.2205,2308.3055,4.758613,4.698954,132.213230,355.12613,4.776180,0.000031,0.396062
371,372.0,21.553947,422.25967,0.002368,1884.2109,1935.2552,4.178522,4.212179,102.148990,321.80123,...,0.004408,2180.4973,2275.5162,4.705935,4.888148,207.395340,344.80135,4.568537,0.000032,0.469921
372,373.0,21.814167,398.68122,0.002508,1914.9557,1969.6716,4.230843,4.697283,243.777110,291.99948,...,0.004045,2141.5764,2229.8147,4.633448,5.210303,450.734520,328.42228,4.303203,0.000034,0.622452

Last 10 rows:

,Temperature (C),Pressure (MPa),"Density (l, kg/m3)","Volume (l, m3/kg)","Internal Energy (l, kJ/kg)","Enthalpy (l, kJ/kg)","Entropy (l, J/g*K)","Cv (l, J/g*K)","Cp (l, J/g*K)","Sound Spd. (l, m/s)",...,"Volume (v, m3/kg)","Internal Energy (v, kJ/kg)","Enthalpy (v, kJ/kg)","Entropy (v, J/g*K)","Cv (v, J/g*K)","Cp (v, J/g*K)","Sound Spd. (v, m/s)","Joule-Thomson (v, K/MPa)","Viscosity (v, Pa*s)","Therm. Cond. (v, W/m*K)"
363,364.0,19.585257,502.78062,0.001989,1766.7109,1805.6648,3.983136,3.433693,19.649326,434.24294,...,0.006203,2314.6935,2436.1900,4.972738,4.158217,37.706719,390.43213,5.702037,0.000027,0.227832
364,365.0,19.821364,495.73968,0.002017,1777.7874,1817.7708,4.001380,3.479720,21.409127,422.54229,...,0.006012,2303.7900,2422.9467,4.949708,4.204760,41.797898,386.93591,5.596199,0.000027,0.240045
365,366.0,20.060120,488.27106,0.002048,1789.3694,1830.4534,4.020478,3.531771,23.594757,410.76177,...,0.005816,2291.9891,2408.6521,4.925115,4.256639,46.972409,383.14646,5.485062,0.000028,0.254189
366,367.0,20.301611,480.29241,0.002082,1801.5611,1843.8303,4.040611,3.590815,26.419178,398.86124,...,0.005614,2279.0925,2393.0758,4.898606,4.315491,53.728408,378.98830,5.367286,0.000028,0.270882
367,368.0,20.545938,471.67141,0.002120,1814.5263,1858.0861,4.062062,3.658568,30.275587,386.69304,...,0.005406,2264.8200,2375.8925,4.869683,4.383756,62.918211,374.35032,5.241003,0.000028,0.291078
368,369.0,20.793214,462.18310,0.002164,1828.5373,1873.5265,4.085300,3.738594,35.945858,373.91929,...,0.005188,2248.7582,2356.6230,4.837611,4.465259,76.121199,369.05993,5.103509,0.000029,0.316341
369,370.0,21.043563,451.42565,0.002215,1844.0715,1890.6872,4.111150,3.838962,45.155176,359.87103,...,0.004954,2230.2593,2334.5183,4.801240,4.566402,96.597620,362.82908,4.950732,0.000030,0.349462
370,371.0,21.297108,438.63778,0.002280,1862.0213,1910.5742,4.141162,3.979315,62.350748,343.27877,...,0.004699,2208.2205,2308.3055,4.758613,4.698954,132.213230,355.12613,4.776180,0.000031,0.396062
371,372.0,21.553947,422.25967,0.002368,1884.2109,1935.2552,4.178522,4.212179,102.148990,321.80123,...,0.004408,2180.4973,2275.5162,4.705935,4.888148,207.395340,344.80135,4.568537,0.000032,0.469921
372,373.0,21.814167,398.68122,0.002508,1914.9557,1969.6716,4.230843,4.697283,243.777110,291.99948,...,0.004045,2141.5764,2229.8147,4.633448,5.210303,450.734520,328.42228,4.303203,0.000034,0.622452

<center>$\rule$</center>
<font size=5><b>4.6 Other Useful Commands For Investigating DataFrames</b></font>

  * <b>df.columns</b>:
  
    * Returns a list-like object containing the column labels.

    * Useful for checking column names or looping through columns.

  * <b>df.index</b>:

    * Returns the row index of the DataFrame (default is a RangeIndex).

    * Important if you're dealing with custom indices like timestamps or labels.

  * <b>df.shape</b>:

    * Returns a tuple representing the dimensions of the DataFrame: (rows, columns).

  * <b>df.dtypes</b>:

    * Shows the data type of each column (e.g., float64, int64, object).

    * Helpful when debugging unexpected behavior in calculations.

  * <b>df.nunique()</b>:

    * Returns the number of unique values in each column.

    * Good for identifying categorical vs. continuous data, or detecting duplicates.

  * <b>df.isnull().sum()</b>:

    * Identifies missing values by column.

    * Essential for cleaning data before analysis or plotting.

  * <b>df.sample(n)</b>:

    * Returns a random sample of n rows from the DataFrame.

    * Great for large datasets when you just want to inspect a few random entries.

  * <b>df["column_name"].value_counts()</b>:

    * For a single column, shows how often each unique value appears (useful for categorical or discrete data).

[Return to Top](#Notebook-Start)

<a name="Select-DF"></a>

---

<font size = 6> <b> 5. Selecting Data in a DataFrame </b> </font>

---

<font size=5><b>5.1 Bracket Notation []</b></font>

<p align="justify">
Once we have loaded and explored our DataFrame, the next step is accessing specific columns or subsets of data. One of the most common and flexible ways to do this is using bracket selection, which looks like: <code>DataFrame[selector]</code>
</p>

<br>

<p align="justify">
Depending on what we put inside the brackets, we can select a column, multiple columns, or filter rows using logical conditions.
</p>

<center>$\rule$</center>
<font size=5><b>5.2 Selecting a Single Column</b></font>

<p align="justify">
If we pass a string (column name) inside the brackets, Pandas returns a Series (a one-dimensional view of that column). This works like selecting a column in a spreadsheet by its header. The result behaves like a list but with labels (index) attached.
</p>

<br>

><b>Note:</b><p align="justify">
We can also call up a column by using: <code>DF_Name.Column_Name</code>
</p>

<br>

<b>Code Example:</b>

In [13]:
# Select the 'Pressure (Mpa)' column of the full data:

pressures = full_data_df['Pressure (MPa)']

# Display the firstnames data:

display(pressures)

0       0.000657
1       0.000706
2       0.000758
3       0.000814
4       0.000873
         ...
368    20.793214
369    21.043563
370    21.297108
371    21.553947
372    21.814167
Name: Pressure (MPa), Length: 373, dtype: float64

<center>$\rule$</center>
<font size=5><b>5.3 Selecting a Multiple Columns</b></font>

<p align="justify">
To select more than one column, pass in a list of column names inside the brackets: <code>subset_df = df[[column_1, column_2]]</code>. Now you get a new DataFrame with just those columns. Similar to hiding other columns in a spreadsheet.
</p>

<br>

<b>Code Example:</b>

In [14]:
# Select the 'Temperature (C)' and 'Pressure (MPa)' columns of the full data DataFrame:

data_subset_df = full_data_df[['Temperature (C)', 'Pressure (MPa)']]

# Display the subset data:

display(data_subset_df)

     Temperature (C)  Pressure (MPa)
0                1.0        0.000657
1                2.0        0.000706
2                3.0        0.000758
3                4.0        0.000814
4                5.0        0.000873
..               ...             ...
368            369.0       20.793214
369            370.0       21.043563
370            371.0       21.297108
371            372.0       21.553947
372            373.0       21.814167

[373 rows x 2 columns]

<center>$\rule$</center>
<font size=5><b>5.4 Selecting Rows with Logical Conditions</b></font>

<p align="justify">
You can also use bracket selection with boolean expressions to filter rows. This is incredibly powerful for working with physical measurements or simulation outputs. This is called using a <b>Boolean Mask</b>. Example: <code>subset = df[boolean_mask]</code>. This filters the DataFrame and only returns rows that meet the condition, just like using filters in Excel or Google Sheets.
</p>

><b>Note:</b><p align="justify">
You can build more complex filters by combining multiple conditions.
</p>

<br>

<b>Code Example:</b>

In [15]:
# Create a subset of data with temperature above 100 C:

high_temp = full_data_df[full_data_df['Temperature (C)'] > 100]

# Display the subset data:

print("High Temperature Data:")
display(high_temp.head())
print()

# Create a subset of data with temperatures between 50 C and 100 C:

medium_temp = full_data_df[(full_data_df['Temperature (C)'] > 50) & (full_data_df['Temperature (C)'] < 100)]

# Display the subset data:

print("Medium Temperature Data:")
display(medium_temp.head())
print()
display(medium_temp.tail())
print()

# Create a subset of data with temperatures below 50 C or above 150 C:

high_and_low_temp = full_data_df[(full_data_df['Temperature (C)'] < 50) | (full_data_df['Temperature (C)'] > 150)]

# Display the subset data:

print("High and Low Temps Only:")
display(high_and_low_temp.head())
print()
display(high_and_low_temp.tail())

High Temperature Data:

,Temperature (C),Pressure (MPa),"Density (l, kg/m3)","Volume (l, m3/kg)","Internal Energy (l, kJ/kg)","Enthalpy (l, kJ/kg)","Entropy (l, J/g*K)","Cv (l, J/g*K)","Cp (l, J/g*K)","Sound Spd. (l, m/s)",...,"Volume (v, m3/kg)","Internal Energy (v, kJ/kg)","Enthalpy (v, kJ/kg)","Entropy (v, J/g*K)","Cv (v, J/g*K)","Cp (v, J/g*K)","Sound Spd. (v, m/s)","Joule-Thomson (v, K/MPa)","Viscosity (v, Pa*s)","Therm. Cond. (v, W/m*K)"
100,101.0,0.105091,957.62913,0.001044,423.27543,423.38517,1.318492,3.762971,4.216833,1542.2641,...,1.617052,2507.2070,2677.1450,7.342172,1.558481,2.084131,472.70368,65.881418,0.000012,0.024668
101,102.0,0.108874,956.90468,0.001045,427.49164,427.60542,1.329746,3.757788,4.218016,1541.3415,...,1.564447,2508.3872,2678.7145,7.330304,1.561174,2.088294,473.20906,65.072364,0.000012,0.024767
102,103.0,0.112768,956.17572,0.001046,431.70900,431.82694,1.340973,3.752614,4.219221,1540.3893,...,1.513858,2509.5632,2680.2784,7.318513,1.563911,2.092531,473.71122,64.279791,0.000012,0.024867
103,104.0,0.116777,955.44227,0.001047,435.92753,436.04975,1.352174,3.747449,4.220450,1539.4078,...,1.465196,2510.7350,2681.8366,7.306799,1.566693,2.096844,474.21014,63.503191,0.000012,0.024967
104,105.0,0.120903,954.70434,0.001047,440.14724,440.27388,1.363347,3.742292,4.221703,1538.3972,...,1.418379,2511.9026,2683.3890,7.295161,1.569520,2.101233,474.70579,62.742071,0.000012,0.025067

Medium Temperature Data:

,Temperature (C),Pressure (MPa),"Density (l, kg/m3)","Volume (l, m3/kg)","Internal Energy (l, kJ/kg)","Enthalpy (l, kJ/kg)","Entropy (l, J/g*K)","Cv (l, J/g*K)","Cp (l, J/g*K)","Sound Spd. (l, m/s)",...,"Volume (v, m3/kg)","Internal Energy (v, kJ/kg)","Enthalpy (v, kJ/kg)","Entropy (v, J/g*K)","Cv (v, J/g*K)","Cp (v, J/g*K)","Sound Spd. (v, m/s)","Joule-Thomson (v, K/MPa)","Viscosity (v, Pa*s)","Therm. Cond. (v, W/m*K)"
50,51.0,0.012978,987.54092,0.001013,213.51085,213.52399,0.716729,4.021533,4.181836,1543.4831,...,11.480639,2444.0583,2593.0548,8.057561,1.467488,1.948420,443.84814,147.45499,0.000011,0.020338
51,52.0,0.013631,987.07916,0.001013,217.69273,217.70654,0.729610,4.016631,4.182141,1544.4971,...,10.962845,2445.3817,2594.8183,8.040426,1.468688,1.950114,444.48488,144.40358,0.000011,0.020415
52,53.0,0.014312,986.61099,0.001014,221.87492,221.88942,0.742453,4.011706,4.182462,1545.4599,...,10.471872,2446.7033,2596.5794,8.023427,1.469906,1.951837,445.11953,141.44986,0.000011,0.020492
53,54.0,0.015022,986.13649,0.001014,226.05743,226.07266,0.755257,4.006759,4.182798,1546.3722,...,10.006168,2448.0230,2598.3380,8.006565,1.471140,1.953588,445.75209,138.59002,0.000011,0.020570
54,55.0,0.015762,985.65573,0.001015,230.24027,230.25626,0.768023,4.001790,4.183150,1547.2346,...,9.564278,2449.3409,2600.0941,7.989836,1.472393,1.955370,446.38251,135.82040,0.000011,0.020648

,Temperature (C),Pressure (MPa),"Density (l, kg/m3)","Volume (l, m3/kg)","Internal Energy (l, kJ/kg)","Enthalpy (l, kJ/kg)","Entropy (l, J/g*K)","Cv (l, J/g*K)","Cp (l, J/g*K)","Sound Spd. (l, m/s)",...,"Volume (v, m3/kg)","Internal Energy (v, kJ/kg)","Enthalpy (v, kJ/kg)","Entropy (v, J/g*K)","Cv (v, J/g*K)","Cp (v, J/g*K)","Sound Spd. (v, m/s)","Joule-Thomson (v, K/MPa)","Viscosity (v, Pa*s)","Therm. Cond. (v, W/m*K)"
94,95.0,0.084608,961.88017,0.001040,398.00100,398.08896,1.250392,3.794214,4.210209,1547.1648,...,1.980556,2500.0419,2667.6138,7.415066,1.543211,2.060652,469.60510,71.112749,0.000012,0.024088
95,96.0,0.087771,961.18314,0.001040,402.21079,402.30210,1.261812,3.788991,4.211258,1546.4250,...,1.913733,2501.2458,2669.2155,7.402712,1.545652,2.064392,470.12930,70.193042,0.000012,0.024183
96,97.0,0.091030,960.48149,0.001041,406.42159,406.51637,1.273203,3.783774,4.212329,1545.6540,...,1.849559,2502.4459,2670.8120,7.390441,1.548135,2.068200,470.65042,69.293281,0.000012,0.024279
97,98.0,0.094390,959.77525,0.001042,410.63344,410.73179,1.284567,3.778563,4.213422,1544.8521,...,1.787914,2503.6421,2672.4033,7.378253,1.550658,2.072077,471.16845,68.412835,0.000012,0.024375
98,99.0,0.097852,959.06443,0.001043,414.84635,414.94838,1.295903,3.773358,4.214537,1544.0197,...,1.728686,2504.8344,2673.9893,7.366146,1.553223,2.076023,471.68335,67.551097,0.000012,0.024473

High and Low Temps Only:

,Temperature (C),Pressure (MPa),"Density (l, kg/m3)","Volume (l, m3/kg)","Internal Energy (l, kJ/kg)","Enthalpy (l, kJ/kg)","Entropy (l, J/g*K)","Cv (l, J/g*K)","Cp (l, J/g*K)","Sound Spd. (l, m/s)",...,"Volume (v, m3/kg)","Internal Energy (v, kJ/kg)","Enthalpy (v, kJ/kg)","Entropy (v, J/g*K)","Cv (v, J/g*K)","Cp (v, J/g*K)","Sound Spd. (v, m/s)","Joule-Thomson (v, K/MPa)","Viscosity (v, Pa*s)","Therm. Cond. (v, W/m*K)"
0,1.0,0.000657,999.85099,0.001,4.176053,4.176710,0.015260,4.215230,4.216599,1407.2064,...,192.43878,2376.2825,2502.7312,9.129083,1.419204,1.885335,409.71719,574.21968,0.000009,0.016824
1,2.0,0.000706,999.89254,0.001,8.391082,8.391788,0.030607,4.212901,4.213496,1412.0752,...,179.75781,2377.6585,2504.5650,9.102652,1.420038,1.886339,410.44043,556.22607,0.000009,0.016889
2,3.0,0.000758,999.91707,0.001,12.603120,12.603879,0.045888,4.210472,4.210617,1416.8302,...,168.00844,2379.0341,2506.3980,9.076466,1.420879,1.887352,411.16199,538.83860,0.000009,0.016953
3,4.0,0.000814,999.92513,0.001,16.812386,16.813199,0.061103,4.207947,4.207947,1421.4738,...,157.11576,2380.4091,2508.2303,9.050521,1.421726,1.888375,411.88188,522.04070,0.000009,0.017018
4,5.0,0.000873,999.91724,0.001,21.019078,21.019951,0.076254,4.205330,4.205470,1426.0080,...,147.01134,2381.7835,2510.0619,9.024814,1.422578,1.889408,412.60012,505.81590,0.000009,0.017083

,Temperature (C),Pressure (MPa),"Density (l, kg/m3)","Volume (l, m3/kg)","Internal Energy (l, kJ/kg)","Enthalpy (l, kJ/kg)","Entropy (l, J/g*K)","Cv (l, J/g*K)","Cp (l, J/g*K)","Sound Spd. (l, m/s)",...,"Volume (v, m3/kg)","Internal Energy (v, kJ/kg)","Enthalpy (v, kJ/kg)","Entropy (v, J/g*K)","Cv (v, J/g*K)","Cp (v, J/g*K)","Sound Spd. (v, m/s)","Joule-Thomson (v, K/MPa)","Viscosity (v, Pa*s)","Therm. Cond. (v, W/m*K)"
368,369.0,20.793214,462.18310,0.002164,1828.5373,1873.5265,4.085300,3.738594,35.945858,373.91929,...,0.005188,2248.7582,2356.6230,4.837611,4.465259,76.121199,369.05993,5.103509,0.000029,0.316341
369,370.0,21.043563,451.42565,0.002215,1844.0715,1890.6872,4.111150,3.838962,45.155176,359.87103,...,0.004954,2230.2593,2334.5183,4.801240,4.566402,96.597620,362.82908,4.950732,0.000030,0.349462
370,371.0,21.297108,438.63778,0.002280,1862.0213,1910.5742,4.141162,3.979315,62.350748,343.27877,...,0.004699,2208.2205,2308.3055,4.758613,4.698954,132.213230,355.12613,4.776180,0.000031,0.396062
371,372.0,21.553947,422.25967,0.002368,1884.2109,1935.2552,4.178522,4.212179,102.148990,321.80123,...,0.004408,2180.4973,2275.5162,4.705935,4.888148,207.395340,344.80135,4.568537,0.000032,0.469921
372,373.0,21.814167,398.68122,0.002508,1914.9557,1969.6716,4.230843,4.697283,243.777110,291.99948,...,0.004045,2141.5764,2229.8147,4.633448,5.210303,450.734520,328.42228,4.303203,0.000034,0.622452

<center>$\rule$</center>
<font size=5><b>5.5 <code>.loc()</code> and <code>.iloc()</code></b></font>

<p align="justify">
Pandas provides two powerful accessors:
</p>

  * .loc[]: selects by label

  * .iloc[]: selects by integer position

<br>

<p align="justify">
These are much more versatile than [] alone, especially when selecting specific rows and columns at the same time or when doing row slicing.
</p>

  * .loc[]: Selection by Label

    * Syntax: <code>df.loc[row_selector, column_selector]</code>

  * Selecting Rows by Index Label

    * Syntax: <code>df.loc[0]  # Selects the row with index label 0</code>

  * Row Slicing by Label

    * Syntax: <code>df.loc[0:2]</code>

    ><b>Note:</b> <code>.loc[]</code> slicing includes the stop value (unlike standard Python slicing).

  * Selecting Specific Rows and Columns by Label

    * Syntax: <code>df.loc[0:2, ["Time (s)", "Velocity (m/s)"]]</code>

    * This returns rows 0 through 2, and only the "Time" and "Velocity" columns.

  * .iloc[]: Selection by Integer Position

    * Syntax: df.iloc[row_index, column_index]

    * Use .iloc[] when you want to slice or select based on numerical index positions, just like Python lists.

  * Selecting a Row by Integer Index

    * df.iloc[0]  # First row

  * Row Slicing by Position

    * df.iloc[0:3]  # Rows 0 through 2 (excludes stop index, like Python slicing)

  * Selecting Specific Rows and Columns by Position

    * df.iloc[0:3, 0:2]  # First 3 rows, first 2 columns

In [16]:
# Use .loc[] to select specific rows and columns by their labels:

selected_data = full_data_df.loc[10:20, ['Temperature (C)', 'Pressure (MPa)']]

# Display the selected data:

print("Selected Data Using .loc[]:")
display(selected_data)
print()

Selected Data Using .loc[]:

    Temperature (C)  Pressure (MPa)
10             11.0        0.001313
11             12.0        0.001403
12             13.0        0.001498
13             14.0        0.001599
14             15.0        0.001706
15             16.0        0.001819
16             17.0        0.001938
17             18.0        0.002065
18             19.0        0.002198
19             20.0        0.002339
20             21.0        0.002488

In [33]:
# Use .iloc[] to select rows and columns by their integer positions:

selected_data = full_data_df.iloc[10:20, 0:2]

# Display the selected data:

print("Selected Data Using .iloc[]:")
display(selected_data)
print()

Selected Data Using .iloc[]:

    Temperature (C)  Pressure (MPa)
10             11.0        0.001313
11             12.0        0.001403
12             13.0        0.001498
13             14.0        0.001599
14             15.0        0.001706
15             16.0        0.001819
16             17.0        0.001938
17             18.0        0.002065
18             19.0        0.002198
19             20.0        0.002339

<center>$\rule$</center> <font size=5><b>5.6 Using the <code>query()</code> Function</b></font> <p align="justify"> We have seen that we can use Boolean masks to carve out specific subsets of data from our DataFrames. However, the syntax can sometimes look a little clunky, especially when we have multiple conditions. </p> <p align="justify"> Fortunately, Pandas provides a simpler, more natural-feeling way to accomplish the same thing using the <b><code>query()</code></b> function. </p>

For example, suppose we want to find all of the saturated-water data where the temperature is above 100°C:

In [30]:
high_temp = full_data_df.query('`Temperature (C)` > 100')

display(high_temp.head())

,Temperature (C),Pressure (MPa),"Density (l, kg/m3)","Volume (l, m3/kg)","Internal Energy (l, kJ/kg)","Enthalpy (l, kJ/kg)","Entropy (l, J/g*K)","Cv (l, J/g*K)","Cp (l, J/g*K)","Sound Spd. (l, m/s)",...,"Internal Energy (v, kJ/kg)","Enthalpy (v, kJ/kg)","Entropy (v, J/g*K)","Cv (v, J/g*K)","Cp (v, J/g*K)","Sound Spd. (v, m/s)","Joule-Thomson (v, K/MPa)","Viscosity (v, Pa*s)","Therm. Cond. (v, W/m*K)",Temperature Range
100,101.0,0.105091,957.62913,0.001044,423.27543,423.38517,1.318492,3.762971,4.216833,1542.2641,...,2507.2070,2677.1450,7.342172,1.558481,2.084131,472.70368,65.881418,0.000012,0.024668,High Temperature
101,102.0,0.108874,956.90468,0.001045,427.49164,427.60542,1.329746,3.757788,4.218016,1541.3415,...,2508.3872,2678.7145,7.330304,1.561174,2.088294,473.20906,65.072364,0.000012,0.024767,High Temperature
102,103.0,0.112768,956.17572,0.001046,431.70900,431.82694,1.340973,3.752614,4.219221,1540.3893,...,2509.5632,2680.2784,7.318513,1.563911,2.092531,473.71122,64.279791,0.000012,0.024867,High Temperature
103,104.0,0.116777,955.44227,0.001047,435.92753,436.04975,1.352174,3.747449,4.220450,1539.4078,...,2510.7350,2681.8366,7.306799,1.566693,2.096844,474.21014,63.503191,0.000012,0.024967,High Temperature
104,105.0,0.120903,954.70434,0.001047,440.14724,440.27388,1.363347,3.742292,4.221703,1538.3972,...,2511.9026,2683.3890,7.295161,1.569520,2.101233,474.70579,62.742071,0.000012,0.025067,High Temperature

<b>Multiple Conditions</b>

We can also combine conditions using 'and' and 'or'.

For example, let's find data where the temperature is between 50°C and 100°C:

In [31]:
medium_temp = full_data_df.query(
    '`Temperature (C)` >= 50 and `Temperature (C)` <= 100'
)

display(medium_temp.head())

,Temperature (C),Pressure (MPa),"Density (l, kg/m3)","Volume (l, m3/kg)","Internal Energy (l, kJ/kg)","Enthalpy (l, kJ/kg)","Entropy (l, J/g*K)","Cv (l, J/g*K)","Cp (l, J/g*K)","Sound Spd. (l, m/s)",...,"Internal Energy (v, kJ/kg)","Enthalpy (v, kJ/kg)","Entropy (v, J/g*K)","Cv (v, J/g*K)","Cp (v, J/g*K)","Sound Spd. (v, m/s)","Joule-Thomson (v, K/MPa)","Viscosity (v, Pa*s)","Therm. Cond. (v, W/m*K)",Temperature Range
49,50.0,0.012352,987.99621,0.001012,209.32926,209.34176,0.703809,4.026410,4.181548,1542.4173,...,2442.7331,2591.2889,8.074835,1.466304,1.946753,443.20934,150.60804,0.000011,0.020261,Low Temperature
50,51.0,0.012978,987.54092,0.001013,213.51085,213.52399,0.716729,4.021533,4.181836,1543.4831,...,2444.0583,2593.0548,8.057561,1.467488,1.948420,443.84814,147.45499,0.000011,0.020338,Medium Temperature
51,52.0,0.013631,987.07916,0.001013,217.69273,217.70654,0.729610,4.016631,4.182141,1544.4971,...,2445.3817,2594.8183,8.040426,1.468688,1.950114,444.48488,144.40358,0.000011,0.020415,Medium Temperature
52,53.0,0.014312,986.61099,0.001014,221.87492,221.88942,0.742453,4.011706,4.182462,1545.4599,...,2446.7033,2596.5794,8.023427,1.469906,1.951837,445.11953,141.44986,0.000011,0.020492,Medium Temperature
53,54.0,0.015022,986.13649,0.001014,226.05743,226.07266,0.755257,4.006759,4.182798,1546.3722,...,2448.0230,2598.3380,8.006565,1.471140,1.953588,445.75209,138.59002,0.000011,0.020570,Medium Temperature

<p align="justify"> Let's suppose that you aren't interested in all of the data in our saturated-water DataFrame, but are instead interested in a specific list of temperatures. </p> <p align="justify"> For example, suppose we want to examine the properties of saturated water at a few temperatures that are particularly relevant to our thermodynamics applications. We'll start by making a list of those temperatures. </p>

In [32]:
list_of_temperatures = [0, 25, 50, 75, 100]

Next, we'll look at our DataFrame and pick out only the rows whose temperature is in that list using the <code>isin()</code> function.

In [33]:
selected_temperatures = full_data_df[
    full_data_df["Temperature (C)"].isin(list_of_temperatures)
]

display(selected_temperatures)

,Temperature (C),Pressure (MPa),"Density (l, kg/m3)","Volume (l, m3/kg)","Internal Energy (l, kJ/kg)","Enthalpy (l, kJ/kg)","Entropy (l, J/g*K)","Cv (l, J/g*K)","Cp (l, J/g*K)","Sound Spd. (l, m/s)",...,"Internal Energy (v, kJ/kg)","Enthalpy (v, kJ/kg)","Entropy (v, J/g*K)","Cv (v, J/g*K)","Cp (v, J/g*K)","Sound Spd. (v, m/s)","Joule-Thomson (v, K/MPa)","Viscosity (v, Pa*s)","Therm. Cond. (v, W/m*K)",Temperature Range
24,25.0,0.003170,997.00335,0.001003,104.82604,104.82922,0.367225,4.137896,4.181600,1496.5368,...,2409.1292,2546.5054,8.556647,1.440500,1.911823,426.62559,278.186150,0.000010,0.018433,Low Temperature
49,50.0,0.012352,987.99621,0.001012,209.32926,209.34176,0.703809,4.026410,4.181548,1542.4173,...,2442.7331,2591.2889,8.074835,1.466304,1.946753,443.20934,150.608040,0.000011,0.020261,Low Temperature
74,75.0,0.038595,974.81496,0.001026,313.99034,314.02993,1.015765,3.899162,4.193340,1554.9485,...,2475.2445,2634.6027,7.681204,1.502010,1.998506,458.51153,94.915265,0.000011,0.022283,Medium Temperature
99,100.0,0.101418,958.34905,0.001043,419.06034,419.16616,1.307211,3.768161,4.215674,1543.1569,...,2506.0227,2675.5699,7.354119,1.555831,2.080041,472.19510,66.707480,0.000012,0.024570,Medium Temperature

<p align="justify"> Again, we can accomplish this task using the <code>query()</code> function. This time, instead of using <code>isin()</code>, we can use the <b><code>in</code></b> operator within our query. </p>

For example, let's use our list of temperatures from above:

In [34]:
selected_temperatures2 = full_data_df.query(
    "`Temperature (C)` in @list_of_temperatures"
)

display(selected_temperatures2)

,Temperature (C),Pressure (MPa),"Density (l, kg/m3)","Volume (l, m3/kg)","Internal Energy (l, kJ/kg)","Enthalpy (l, kJ/kg)","Entropy (l, J/g*K)","Cv (l, J/g*K)","Cp (l, J/g*K)","Sound Spd. (l, m/s)",...,"Internal Energy (v, kJ/kg)","Enthalpy (v, kJ/kg)","Entropy (v, J/g*K)","Cv (v, J/g*K)","Cp (v, J/g*K)","Sound Spd. (v, m/s)","Joule-Thomson (v, K/MPa)","Viscosity (v, Pa*s)","Therm. Cond. (v, W/m*K)",Temperature Range
24,25.0,0.003170,997.00335,0.001003,104.82604,104.82922,0.367225,4.137896,4.181600,1496.5368,...,2409.1292,2546.5054,8.556647,1.440500,1.911823,426.62559,278.186150,0.000010,0.018433,Low Temperature
49,50.0,0.012352,987.99621,0.001012,209.32926,209.34176,0.703809,4.026410,4.181548,1542.4173,...,2442.7331,2591.2889,8.074835,1.466304,1.946753,443.20934,150.608040,0.000011,0.020261,Low Temperature
74,75.0,0.038595,974.81496,0.001026,313.99034,314.02993,1.015765,3.899162,4.193340,1554.9485,...,2475.2445,2634.6027,7.681204,1.502010,1.998506,458.51153,94.915265,0.000011,0.022283,Medium Temperature
99,100.0,0.101418,958.34905,0.001043,419.06034,419.16616,1.307211,3.768161,4.215674,1543.1569,...,2506.0227,2675.5699,7.354119,1.555831,2.080041,472.19510,66.707480,0.000012,0.024570,Medium Temperature

<p align="justify"> As before, the <b><code>query()</code></b> function makes it easy and natural to ask multiple questions of our data at once. </p>

<p align="justify"> For example, let's start with our list of selected temperatures, but now we'll add another condition. Suppose we only want the temperatures in our list that correspond to sound speeds <b>greater than or equal to 450 m/s</b>. </p>

In [35]:
selected_data = full_data_df.query(
    "`Temperature (C)` in @list_of_temperatures and `Sound Spd. (v, m/s)` >= 450"
)

display(selected_data)

,Temperature (C),Pressure (MPa),"Density (l, kg/m3)","Volume (l, m3/kg)","Internal Energy (l, kJ/kg)","Enthalpy (l, kJ/kg)","Entropy (l, J/g*K)","Cv (l, J/g*K)","Cp (l, J/g*K)","Sound Spd. (l, m/s)",...,"Internal Energy (v, kJ/kg)","Enthalpy (v, kJ/kg)","Entropy (v, J/g*K)","Cv (v, J/g*K)","Cp (v, J/g*K)","Sound Spd. (v, m/s)","Joule-Thomson (v, K/MPa)","Viscosity (v, Pa*s)","Therm. Cond. (v, W/m*K)",Temperature Range
74,75.0,0.038595,974.81496,0.001026,313.99034,314.02993,1.015765,3.899162,4.193340,1554.9485,...,2475.2445,2634.6027,7.681204,1.502010,1.998506,458.51153,94.915265,0.000011,0.022283,Medium Temperature
99,100.0,0.101418,958.34905,0.001043,419.06034,419.16616,1.307211,3.768161,4.215674,1543.1569,...,2506.0227,2675.5699,7.354119,1.555831,2.080041,472.19510,66.707480,0.000012,0.024570,Medium Temperature

[Return to Top](#Notebook-Start)

<a name="Select-DF"></a>

---

<font size = 6> <b> 6. Groupby Operations </b> </font>

---

## Group Saturated Water Data by Temperature Range

Let's say that we want to find out information about specific temperature ranges within our DataFrame. We can do so by grouping our entries based on some criteria.

For example, let's group the saturated-water data based on the temperature of the water.

To make our groups more useful, we will create three temperature categories:

1) Low Temperature: below 50°C
2) Medium Temperature: 50°C - 100°C
3) High Temperature: above 100°C

We will then examine the temperature, saturation pressure, and enthalpy of the water within each group.

In [19]:
# Create a new column that categorizes the data based on temperature:

full_data_df["Temperature Range"] = pd.cut(
    full_data_df["Temperature (C)"],
    bins=[-float("inf"), 50, 100, float("inf")],
    labels=["Low Temperature", "Medium Temperature", "High Temperature"]
)

# Group the data by temperature range:

grouped_by_temp = full_data_df.groupby(
    "Temperature Range",
    observed=True
)[
    ["Temperature (C)", "Pressure (MPa)", "Enthalpy (l, kJ/kg)"]
]

Let's now examine our new grouping.

In [18]:
print("Grouped By Temperature Range DataFrame Head:")

print()

print(grouped_by_temp.head())

print()
print()

print("Grouped By Temperature Range DataFrame Tail:")

print()

print(grouped_by_temp.tail())

Grouped By Temperature Range DataFrame Head:

     Temperature (C)  Pressure (MPa)  Enthalpy (l, kJ/kg)
0                1.0        0.000657             4.176710
1                2.0        0.000706             8.391788
2                3.0        0.000758            12.603879
3                4.0        0.000814            16.813199
4                5.0        0.000873            21.019951
50              51.0        0.012978           213.523990
51              52.0        0.013631           217.706540
52              53.0        0.014312           221.889420
53              54.0        0.015022           226.072660
54              55.0        0.015762           230.256260
100            101.0        0.105091           423.385170
101            102.0        0.108874           427.605420
102            103.0        0.112768           431.826940
103            104.0        0.116777           436.049750
104            105.0        0.120903           440.273880


Grouped By Temperature Range DataFrame Tail:

     Temperature (C)  Pressure (MPa)  Enthalpy (l, kJ/kg)
45              46.0        0.010099            192.61568
46              47.0        0.010627            196.79681
47              48.0        0.011177            200.97819
48              49.0        0.011752            205.15983
49              50.0        0.012352            209.34176
95              96.0        0.087771            402.30210
96              97.0        0.091030            406.51637
97              98.0        0.094390            410.73179
98              99.0        0.097852            414.94838
99             100.0        0.101418            419.16616
368            369.0       20.793214           1873.52650
369            370.0       21.043563           1890.68720
370            371.0       21.297108           1910.57420
371            372.0       21.553947           1935.25520
372            373.0       21.814167           1969.67160

It's hard to tell what's going on just from the above. Python has created a group for each temperature range and assigned each row to its appropriate group.

We can, however, perform operations on the groupings.

For example, we can find the average temperature, saturation pressure, and enthalpy of the water within each temperature range using the mean() function.

<b>
numeric_only = True
</b>

This tells Python that we only want to calculate averages for columns that contain numerical values. This is particularly useful when our DataFrame also contains categorical or text-based columns, such as our "Temperature Range" column.

Let's calculate the average properties for each temperature range:

In [23]:
average_properties_by_range = full_data_df.groupby(
    "Temperature Range",
    observed = True
).mean(numeric_only=True)

average_properties_by_range

,Temperature (C),Pressure (MPa),"Density (l, kg/m3)","Volume (l, m3/kg)","Internal Energy (l, kJ/kg)","Enthalpy (l, kJ/kg)","Entropy (l, J/g*K)","Cv (l, J/g*K)","Cp (l, J/g*K)","Sound Spd. (l, m/s)",...,"Volume (v, m3/kg)","Internal Energy (v, kJ/kg)","Enthalpy (v, kJ/kg)","Entropy (v, J/g*K)","Cv (v, J/g*K)","Cp (v, J/g*K)","Sound Spd. (v, m/s)","Joule-Thomson (v, K/MPa)","Viscosity (v, Pa*s)","Therm. Cond. (v, W/m*K)"
Temperature Range,,,,,,,,,,,,,,,,,,,,,
Low Temperature,25.5,0.004360,995.866067,0.001004,106.866131,106.870522,0.369164,4.130764,4.187077,1489.921728,...,60.935237,2409.705190,2547.273096,8.565342,1.441544,1.913630,426.794386,304.316170,0.000010,0.018494
Medium Temperature,75.5,0.045521,973.972951,0.001027,316.155530,316.202503,1.018381,3.895977,4.195421,1550.918752,...,4.877616,2475.589180,2635.055334,7.685069,1.505924,2.004792,458.531538,98.521056,0.000011,0.022370
High Temperature,237.0,5.690380,787.826275,0.001314,1050.033873,1059.117578,2.675669,3.306486,7.593491,1125.485715,...,0.220036,2540.693648,2722.138155,6.154759,2.521925,9.782632,479.253134,23.131287,0.000018,0.068923

We can instead find the least value in a group by using the <b>min()</b> function

For example, let's find the minimum enthalpy within each of our temperature ranges.

In [25]:
least_enthalpy = minimum_properties_by_range = full_data_df.groupby(
    "Temperature Range",
    observed = True
)["Enthalpy (l, kJ/kg)"].min()

display(least_enthalpy)

Temperature Range
Low Temperature         4.17671
Medium Temperature    213.52399
High Temperature      423.38517
Name: Enthalpy (l, kJ/kg), dtype: float64

Or, we can find the largest value within each group by using the <b>max()</b> function.

In [26]:
most_enthalpy = minimum_properties_by_range = full_data_df.groupby(
    "Temperature Range",
    observed = True
)["Enthalpy (l, kJ/kg)"].max()

display(most_enthalpy)

Temperature Range
Low Temperature        209.34176
Medium Temperature     419.16616
High Temperature      1969.67160
Name: Enthalpy (l, kJ/kg), dtype: float64

We can even make up our own functions to parse the data by using the <b>agg()</b> function which stands for "aggregate".

For example, let's create a function that calculates the range of a thermodynamic property within each temperature range.

In [29]:
def property_range(value_list):

    largest = max(value_list)

    smallest = min(value_list)

    return largest - smallest

pressure_range_by_temp = full_data_df.groupby(
    "Temperature Range",
    observed=True
)[["Pressure (MPa)"]].agg(property_range)

pressure_range_by_temp = pressure_range_by_temp.rename(
    columns={"Pressure (MPa)": "Pressure Range (MPa)"}
)

display(pressure_range_by_temp)

                    Pressure Range (MPa)
Temperature Range
Low Temperature                 0.011695
Medium Temperature              0.088440
High Temperature               21.709076

<b>Some useful built-in functions</b>

| Function | What it calculates | Example          |
| -------- | ------------------ | ---------------- |
| `mean`   | Average value      | `.agg("mean")`   |
| `min`    | Smallest value     | `.agg("min")`    |
| `max`    | Largest value      | `.agg("max")`    |
| `sum`    | Sum of all values  | `.agg("sum")`    |
| `count`  | Number of values   | `.agg("count")`  |
| `median` | Middle value       | `.agg("median")` |
| `std`    | Standard deviation | `.agg("std")`    |
| `var`    | Variance           | `.agg("var")`    |